<?php

namespace TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findCategoryByUser($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM TaskBundle:Category c WHERE c.user = :id ORDER BY c.name ASC");
        $query->setParameter('id', $id);
        $categories = $query->getResult();
        
        return $categories;
    }
}
