<?php

namespace TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findCommentsByTaskId($id){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery('SELECT c FROM TaskBundle:Comment c WHERE c.task = :id ORDER BY c.date DESC');
        $query->setParameter('id', $id);
        
        return $query->getResult();
    }
}
